server:
  port: 8081

spring:
  profiles:
    active: cred
---
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${client-id}
            client-secret: ${client-secret}